import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="min-h-screen bg-black text-white"
      >
        <nav className="sticky top-0 z-50 py-5 border-b bg-red-600/70 backdrop-blur">
          <div className="mx-auto flex max-w-5l items-center justify-between px-6 px-4">
            <a href="/" className="font-semibold">Moin</a>
            <div className="flex gap-6 text-sm">
              <a href="/projects" className="hover:underline">Projects</a>
              <a href="/blog " className="hover:underline">Blog</a>
            </div>
          </div>
        </nav>
        {children}

        <footer className="mt-20 flex border-t border-white/10 py-6 bg-red-600/70">
          <div className="mx-auto max-w-5xl px-6 text-sm text-gray-400 flex justify-between ">
            <span>© {new Date().getFullYear()} Moin Palekar</span>
          </div>
        </footer>

      </body>
    </html>
  );
}
